### ISSUE TITLE
RuntimeError: uvloop does not support Windows at the moment

### ISSUE THREAD

**Issue by benpowis** [google-marketing-solutions/description_genius#17]
Hi guys,
I am getting the following error when installing dependencies, anything I can do to get around this?
```

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\...\AppData\Local\Temp\pip-install-19tf52qh\uvloop_d9b57a2ae4b54a01962e1175aed43130\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]
```

**Comment by eqadir** [comment]
HI, we noticed some dependency issues creep up after some dependabot updates. Could you please retry pip installing the requirements within the latest version of the repo? This should hopefully fix it. Thanks!

**Comment by jakubcurik** [comment]
Hello, even with the latest version, I'm also experiencing an issue with the uvloop package. It's not compatible with Windows. What exactly is the function of this package in your code? I tried removing it from the requirements.txt so it isn't installed, and everything works just fine.

**Comment by eqadir** [comment]
The uvloop library is not a direct dependency of Description Genius but comes as a nested dependency and gets put in requirements.txt as a result of pip freeze. Removing it from requirements appears to be the correct choice for windows users. Hope that helps!
